[features]
seeds = false
skip-lint = false

[programs.localnet]
myepicproject = "FBqBwPmnysxnemW2MfDXPDpJQMKUdLnTK91gUXzXqEGs"

[programs.devnet]
myepicproject = "FBqBwPmnysxnemW2MfDXPDpJQMKUdLnTK91gUXzXqEGs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rocha/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
