[features]
seeds = false
skip-lint = false

[programs.localnet]
myepicproject = "2az91BTX5hAPNBp8QyrP3puxUAfMPqCL8N3N71FHY12Y"

[programs.devnet]
myepicproject = "2az91BTX5hAPNBp8QyrP3puxUAfMPqCL8N3N71FHY12Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rocha/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
